import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Frontend Mentor | E-commerce product page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* ///// code here ///// */}
      Collections Men Women About Contact Sneaker Company Fall Limited Edition
      Sneakers These low-profile sneakers are your perfect casual wear
      companion. Featuring a durable rubber outer sole, they’ll withstand
      everything the weather can offer. $125.00 50% $250.00 0 Add to cart
      <div className="attribution">
        Challenge by{" "}
        <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">
          Frontend Mentor
        </a>
        . Coded by <a href="#">Your Name Here</a>.
      </div>
      {/* ///// code here ///// */}
    </div>
  );
}
